image:
  file: .gitpod.dockerfile
tasks:
  - before: printf "\n[settings]\napi_key = $WAKATIME_API_KEY\n" > ~/.wakatime.cfg
  - init: yarn install
    command: 'echo "TODO: Replace with command to start project"'
