image:
  file: .gitpod.dockerfile
tasks:
  - before: printf "\n[settings]\napi_key = $WAKATIME_API_KEY\n" > ~/.wakatime.cfg
  - command: openssl req -nodes -x509 -subj '/CN=localhost' -keyout dev.key -out dev.cert
  - init: yarn install
    command: 'echo "TODO: Replace with command to start project"'
  