tasks:
  - before: printf "\n[settings]\napi_key = $WAKATIME_API_KEY\n" > ~/.wakatime.cfg
  - command: mkdir ssl && openssl req -nodes -x509 -subj '/CN=localhost' -keyout ./ssl/dev.key -out ./ssl/dev.cert
  - init: yarn install
    command: yarn build && yarn start
  