// Show users request
GET https://localhost:8080/users

###

// Change username request
POST https://localhost:8080/users/changeemail
Content-Type: application/json

{
    "email": "louis@hotmail.com",
    "id": 24
}