// Show users request
GET https://localhost:8080/users

###

// Change password request
POST https://localhost:8080/users/changepassword
Content-Type: application/json

{
    "password": "testingPassword",
    "id": 24
}