// Show users request
GET https://localhost:8080/api/users

###

// Register request
POST https://localhost:8080/api/users/
Content-Type: application/json

{
    "email": "louisM@gmail.com",
    "password": "passWord123"
}

###

// Delete request
DELETE https://localhost:8080/api/users/:userID
Content-Type: application/json

###

// Login request
POST https://localhost:8080/api/users/login
Content-Type: application/json

{
    "email": "louis3@gmail.com",
    "password": "testPassword"
}

###

// Change username request ('id' will vary)
PATCH https://localhost:8080/api/users/13193204077821952
Content-Type: application/json

{ 
    "username": "testname12"
}

###

// Change password request ('id' will vary)
PATCH https://localhost:8080/api/users/13193204077821952
Content-Type: application/json

{ 
    "password": "testingPassword"
}

###

// Change email request ('id' will vary) 
PATCH https://localhost:8080/api/users/13193204077821952
Content-Type: application/json

{ 
    "email": "testname12.1@gmail.com"
}